package test_pkg;
// Generated 01.12.2016 18:08:35 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Attributes generated by hbm2java
 */
public class Attributes  implements java.io.Serializable {


     private BigDecimal attributeId;
     private ObjectsTypes objectsTypes;
     private AttributeTypes attributeTypes;
     private String name;

    public Attributes() {
    }

	
    public Attributes(BigDecimal attributeId) {
        this.attributeId = attributeId;
    }
    public Attributes(BigDecimal attributeId, ObjectsTypes objectsTypes, AttributeTypes attributeTypes, String name) {
       this.attributeId = attributeId;
       this.objectsTypes = objectsTypes;
       this.attributeTypes = attributeTypes;
       this.name = name;
    }
   
    public BigDecimal getAttributeId() {
        return this.attributeId;
    }
    
    public void setAttributeId(BigDecimal attributeId) {
        this.attributeId = attributeId;
    }
    public ObjectsTypes getObjectsTypes() {
        return this.objectsTypes;
    }
    
    public void setObjectsTypes(ObjectsTypes objectsTypes) {
        this.objectsTypes = objectsTypes;
    }
    public AttributeTypes getAttributeTypes() {
        return this.attributeTypes;
    }
    
    public void setAttributeTypes(AttributeTypes attributeTypes) {
        this.attributeTypes = attributeTypes;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


