package test_pkg;
// Generated 01.12.2016 18:08:35 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * AttributeTypes generated by hbm2java
 */
public class AttributeTypes  implements java.io.Serializable {


     private BigDecimal attributeTypeId;
     private String name;
     private Set<Attributes> attributeses = new HashSet<Attributes>(0);

    public AttributeTypes() {
    }

	
    public AttributeTypes(BigDecimal attributeTypeId) {
        this.attributeTypeId = attributeTypeId;
    }
    public AttributeTypes(BigDecimal attributeTypeId, String name, Set<Attributes> attributeses) {
       this.attributeTypeId = attributeTypeId;
       this.name = name;
       this.attributeses = attributeses;
    }
   
    public BigDecimal getAttributeTypeId() {
        return this.attributeTypeId;
    }
    
    public void setAttributeTypeId(BigDecimal attributeTypeId) {
        this.attributeTypeId = attributeTypeId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Attributes> getAttributeses() {
        return this.attributeses;
    }
    
    public void setAttributeses(Set<Attributes> attributeses) {
        this.attributeses = attributeses;
    }




}


