package test_pkg;
// Generated 01.12.2016 18:08:35 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * ObjectsTypes generated by hbm2java
 */
public class ObjectsTypes  implements java.io.Serializable {


     private BigDecimal objectTypeId;
     private ObjectsTypes objectsTypes;
     private String name;
     private String description;
     private Set<ObjectsTypes> objectsTypeses = new HashSet<ObjectsTypes>(0);
     private Set<Attributes> attributeses = new HashSet<Attributes>(0);
     private Set<Objects> objectses = new HashSet<Objects>(0);

    public ObjectsTypes() {
    }

	
    public ObjectsTypes(BigDecimal objectTypeId) {
        this.objectTypeId = objectTypeId;
    }
    public ObjectsTypes(BigDecimal objectTypeId, ObjectsTypes objectsTypes, String name, String description, Set<ObjectsTypes> objectsTypeses, Set<Attributes> attributeses, Set<Objects> objectses) {
       this.objectTypeId = objectTypeId;
       this.objectsTypes = objectsTypes;
       this.name = name;
       this.description = description;
       this.objectsTypeses = objectsTypeses;
       this.attributeses = attributeses;
       this.objectses = objectses;
    }
   
    public BigDecimal getObjectTypeId() {
        return this.objectTypeId;
    }
    
    public void setObjectTypeId(BigDecimal objectTypeId) {
        this.objectTypeId = objectTypeId;
    }
    public ObjectsTypes getObjectsTypes() {
        return this.objectsTypes;
    }
    
    public void setObjectsTypes(ObjectsTypes objectsTypes) {
        this.objectsTypes = objectsTypes;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set<ObjectsTypes> getObjectsTypeses() {
        return this.objectsTypeses;
    }
    
    public void setObjectsTypeses(Set<ObjectsTypes> objectsTypeses) {
        this.objectsTypeses = objectsTypeses;
    }
    public Set<Attributes> getAttributeses() {
        return this.attributeses;
    }
    
    public void setAttributeses(Set<Attributes> attributeses) {
        this.attributeses = attributeses;
    }
    public Set<Objects> getObjectses() {
        return this.objectses;
    }
    
    public void setObjectses(Set<Objects> objectses) {
        this.objectses = objectses;
    }




}


