package test_pkg;
// Generated 01.12.2016 18:08:35 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Objects generated by hbm2java
 */
public class Objects  implements java.io.Serializable {


     private BigDecimal objectId;
     private Objects objects;
     private ObjectsTypes objectsTypes;
     private String name;
     private String description;
     private Set<Objects> objectses = new HashSet<Objects>(0);

    public Objects() {
    }

	
    public Objects(BigDecimal objectId) {
        this.objectId = objectId;
    }
    public Objects(BigDecimal objectId, Objects objects, ObjectsTypes objectsTypes, String name, String description, Set<Objects> objectses) {
       this.objectId = objectId;
       this.objects = objects;
       this.objectsTypes = objectsTypes;
       this.name = name;
       this.description = description;
       this.objectses = objectses;
    }
   
    public BigDecimal getObjectId() {
        return this.objectId;
    }
    
    public void setObjectId(BigDecimal objectId) {
        this.objectId = objectId;
    }
    public Objects getObjects() {
        return this.objects;
    }
    
    public void setObjects(Objects objects) {
        this.objects = objects;
    }
    public ObjectsTypes getObjectsTypes() {
        return this.objectsTypes;
    }
    
    public void setObjectsTypes(ObjectsTypes objectsTypes) {
        this.objectsTypes = objectsTypes;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set<Objects> getObjectses() {
        return this.objectses;
    }
    
    public void setObjectses(Set<Objects> objectses) {
        this.objectses = objectses;
    }




}


